# Set memory settings for the Gradle daemon
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# Android specific settings
android.useAndroidX=true
android.enableJetifier=true

# Workaround for AAPT2 link timeouts/crashes in some environments
# android.aapt2.parallelResourceProcessing=false
